import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import PreviewForm from '../components/PreviewForm';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PreviewForm />
  </>

);

export default Home;
